### PR TITLE
fix: empty word

### LINKED ISSUE #200: Empty words on cards are not empty when viewing a deck
View deck: let empty words be empty (don't show 'translation')

### PR DESCRIPTION
**Pull request by blendaf**
fixes #200

### CODE REVIEW

File: components/deck/WordCard.js [hunk 1]
```diff
@@ -42,9 +42,9 @@ const Seperator = styled.hr`
 export default ({ card }) => {
   return (
     <WordCard>
-      <Word>{card.original ? card.original : 'Original Word'}</Word>
+      <Word>{card.original ? card.original : ''}</Word>
```
Comment (juliuscc) [inline components/deck/WordCard.js]: I think this is more readable

```suggestion
      <Word>{card.original}</Word>
```

**Review by juliuscc — APPROVED** [review]
LGTM :)
