### PR TITLE
Fix/search result headers

### LINKED ISSUE #128: Add title to translation result columns

### PR DESCRIPTION
**Pull request by Falcasantos**
Fixes #128

### CODE REVIEW

**Review by blendaf — APPROVED** [review]
LGTM

File: components/exchange/Translation.js [hunk 1]
```diff
@@ -66,8 +66,9 @@ const TranslationContainer = styled.div`
 const WordContainer = styled.div`
   display: grid;
   grid-column-gap: 10px;
-  grid-auto-flow: row;
-  align-content: center;
+  // grid-auto-flow: row;
+  // align-content: center;
```
Comment (juliuscc) [inline components/exchange/Translation.js]: Let's not merge with these comments

**Review by juliuscc — CHANGES_REQUESTED** [review]

File: components/exchange/Translation.js (hunk 1 above)
Comment (Falcasantos) [reply components/exchange/Translation.js]: Done

**Review by juliuscc — APPROVED** [review]
