### PR TITLE
fix: adds responsive layout

### LINKED ISSUE #156: Browse deck is not a mobile friendly design

### PR DESCRIPTION
**Pull request by blendaf**
fixes #156 #81

### CODE REVIEW

File: components/browse-decks/DeckSearch.js [hunk 1]
```diff
@@ -8,13 +9,22 @@ const DeckSearch = styled.div`
...
+    align-items: center;
+  }
 `
 const SearchBar = styled.div`
   display: flex;
   flex-direction: row;
   padding-bottom: 10px;
   height: 50px;
-  width: 100%;
+  width: 280px;
```
Comment (juliuscc) [inline components/browse-decks/DeckSearch.js:24]: Why is it like this? Is this because that the pills have this size?

Comment (blendaf) [reply components/browse-decks/DeckSearch.js:24]: yes, width 100% didn't want to work

**Review by juliuscc — APPROVED** [review]
